version: 0.0
os: linux
files:
  - source: /
    destination: /home/ssm-user/node-app/
hooks:
  AfterInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu


# version: 0.0
# os: linux
# files:
#   - source: /
#     destination: /var/nodeapp/
# hooks:
#   AfterInstall:
#     - location: scripts/npm-install.sh
#       timeout: 300
#   ApplicationStart:
#     - location: scripts/start_server.sh
#       timeout: 60
#   ApplicationStop:
#     - location: scripts/stop_server.sh
#       timeout: 300
